cc_library(
    name = "ranker",
    hdrs = ["Ranker.h"],
    deps = ["//ranker:ranker_consts"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "ranker_consts",
    hdrs = ["ranker_consts.h"],
    visibility = ["//visibility:public"],
)