#pragma once

#include <cstring>
#include "string.h"

// Source: https://github.com/BurntRouter/filtered-word-lists/blob/master/worldfilter_blanketbanned
static constexpr const char* BLOCKED_URL_KEYWORDS[] = {
    "milf",
    "nazi",
    "orgy",
    "porn",
    "p0rn",
    "pussy",
    "pussi",
    "pusse",
    "niggar",
    "nigga",
    "nigger",
    "nigg3r",
    "nigg4h",
    "n1gga",
    "n1gger",
    "assfuck",
    "b00b",
    "ballsack",
    "beastial",
    "bestial",
    "blowjob",
    "boner",
    "boob",
    "buttplug",
    "c0ck",
    "chink",
    "cl1t",
    "clit",
    "cockface",
    "cockhead",
    "cockmunch",
    "cocksuck",
    "cocksuka",
    "cocksukka",
    "cokmuncher",
    "coksucka",
    "cummer",
    "cumshot",
    "cuniling",
    "cuntlick",
    "cunts",
    "cyalis",
    "cyberfuc",
    "d1ck",
    "dickhead",
    "dildo",
    "dog-fucker",
    "doggin",
    "donkeyribber",
    "doosh",
    "douche",
    "duche",
    "ejaculat",
    "ejakulate",
    "f4nny",
    "fagg",
    "fagot",
    "fatass",
    "felch",
    "fellat",
    "fingerfuck",
    "fistfuck",
    "fuckhead",
    "fuckme",
    "fuckwhit",
    "fuckwit",
    "fukwit",
    "fukwhit",
    "gangbang",
    "gaysex",
    "goatse",
    "hardcoresex",
    "horniest",
    "horny",
    "hotsex",
    "jack-off",
    "jackoff",
    "jerk-off",
    "jism",
    "jizm",
    "jizz",
    "kawk",
    "kondum",
    "kummer",
    "kunilingus",
    "l3itch",
    "labia",
    "m0f0",
    "m0fo",
    "m45terbate",
    "ma5terb8",
    "ma5terbate",
    "masochist",
    "master-bate",
    "masterb8",
    "masterbat",
    "masturbat",
    "nutsack",
    "orgasim",
    "orgasm",
    "penis",
    "phonesex",
    "phuck",
    "phuk",
    "pigfucker",
    "pissoff",
    "rectum",
    "rimjaw",
    "sadist",
    "schlong",
    "scrotum",
    "shagg",
    "shitdick",
    "shitfuck",
    "shithead",
    "slut",
    "smegma",
    "spunk",
    "t1tt",
    "testical",
    "testicle",
    "titfuck",
    "tittie",
    "tittyfuck",
    "tittywank",
    "titwank",
    "tw4t",
    "twathead",
    "twatty",
    "twunt",
    "v14gra",
    "v1gra",
    "vagina",
    "viagra",
    "vulva",
    "w00se",
    "wanker",
    "wanky",
    "whore",
    "xrated",
    "xxx",
    "xvideos",
    "xnxx",
    "xhamster",
    "redtube",
    "brazzers",
    "hentai",
    "rule34",
    "onlyfans",
    "chaturbate",
    "livejasmin",
    "stripchat",
    "bongacams",
    "cam4",
    "fapello",
    "spankbang",
    "eporner",
    "tube8",
    "beeg",
    "xossip",
    "motherless",
    "xtube",
    "tnaflix",
    "nuvid",
    "fuq",
    "nsfw",
    "anal",
    "creampie",
    "handjob",
    "threesome",
    "fetish",
    "bondage",
    "escort",
    "sexcam",
    "camgirl",
    "nude",
    "naked",
    "erotic",
    "playboy",
    "penthouse",
    "hustler",
    "backpage",
    "bedpage",
    "adultsearch",
    "adultfriendfinder",
};

static constexpr size_t BLOCKED_URL_KEYWORDS_COUNT = sizeof(BLOCKED_URL_KEYWORDS) / sizeof(BLOCKED_URL_KEYWORDS[0]);

inline bool url_contains_ci(const char* haystack, size_t haystack_len, const char* needle) {
    size_t needle_len = strlen(needle);
    if (needle_len > haystack_len) return false;
    for (size_t i = 0; i <= haystack_len - needle_len; i++) {
        bool match = true;
        for (size_t j = 0; j < needle_len; j++) {
            if (tolower((unsigned char)haystack[i + j]) != tolower((unsigned char)needle[j])) {
                match = false;
                break;
            }
        }
        if (match) return true;
    }
    return false;
}

inline bool is_nsfw_url(const string& url) {
    for (size_t i = 0; i < BLOCKED_URL_KEYWORDS_COUNT; i++) {
        if (url_contains_ci(url.data(), url.size(), BLOCKED_URL_KEYWORDS[i]))
            return true;
    }
    return false;
}
