cc_library(
    name = "expressions",
    hdrs = ["expressions.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "query_helpers",
    hdrs = ["query_helpers.h"],
    visibility = ["//visibility:public"],
)